# Generated by Django 3.2.5 on 2022-05-12 15:05
import json

from django.db import migrations, models


def create_catalogs(apps, schema_editor):
    Cities = apps.get_model("search_app", "Cities")
    # db_alias = schema_editor.connection.alias
    with open("search_app/migrations/cities-canada-usa.json", encoding="utf8") as file:
        cities_json = json.load(file)
        Cities.objects.bulk_create(
            (
                Cities(id=data['id'],
                       name=data['name'],
                       lat=data['lat'],
                       long=data['long']
                       )
                for data in cities_json
            ),
            ignore_conflicts=True
        )


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('long', models.DecimalField(decimal_places=6, max_digits=9)),
            ],
        ),

        migrations.RunPython(
            create_catalogs,
            reverse_code=migrations.RunPython.noop
        )
    ]
