# Generated by Django 3.2.5 on 2022-05-13 17:00
from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search_app', '0001_initial'),
    ]

    operations = [
        TrigramExtension()
    ]
